### ISSUE TITLE
Allow specifying output directory

### ISSUE THREAD

**Issue by CaselIT** [RalfG/python-wheels-manylinux-build#13]
Currently the wheels are placed in the `wheelhouse` folder, instead of the standard `dist`.

I think it would be nice to have a input to specify the destination folder.
The default can remain `wheelhouse`

**Comment by RalfG** [comment]
I actually thought of changing the default to `dist` in a future version, as it makes more sense. For some reason `wheelhouse` is used in the manylinux container example script.

But an input for the destination folder is a good idea!

**Comment by mrmundt** [comment]
I would second this opinion! 

A thought on this: You already have an option for users to utilize `pip-wheel-args` in the action. Why not remove the `-w /github/workspace/wheelhouse/` assumption? Or allow for an override there?

**Comment by RalfG** [comment]
@mrmundt: I fully agree! I'll make this an option in the next version.
