### ISSUE TITLE
compatible with pybind11?

### ISSUE THREAD

**Issue by xiuliren** [RalfG/python-wheels-manylinux-build#15]
Hi, thanks for this great package.
I used pybind11 rather than Cython. 
It seems that this package requires Cython. is there a way to work around?

```
ERROR: Directory '/github/workspace/' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
+ echo 'Building wheels failed.'
Building wheels failed.
+ exit 1
```

**Comment by RalfG** [comment]
Hi! 
As long as it is a Python package ([build with setuptools](https://pybind11.readthedocs.io/en/stable/compiling.html#building-with-setuptools)), it should work, regardless of Cython or pybind.
It seems like the build script cannot find a `setup.py` or `pyproject.toml` file. How do you build the package locally?

**Comment by xiuliren** [comment]
thank you. I use `python setup.py install` to install it. It seems an issue of finding setup.py file. It probably is not an issue of this package.
