### ISSUE TITLE
Add option to produce GitHub artifacts 

### ISSUE THREAD

**Issue by rcarcasses** [RalfG/python-wheels-manylinux-build#16]
As far as I have understood this GitHub Action allows to produce fixed wheels and push it automatically to public registry. I wonder if we could take the output of this build process and upload it to private registries, for instance, or to produce artifacts that we could use with [actions/upload-artifact@v1](https://github.com/actions/upload-artifact). Any ideas?

**Comment by RalfG** [comment]
This action only builds the wheels. They can then be uploaded using e.g. Twine in a next workflow step. Similarly, you can append any actions, and do with the wheel files what you want. In the current version ([v0.2.2](https://github.com/RalfG/python-wheels-manylinux-build/releases/tag/v0.2.2)), the wheels are placed in the `wheelhouse` directory. 

For example, you can use the upload-artifact action, as you suggested, by adding this step:
```
- uses: actions/upload-artifact@v2-preview
  with:
    name: wheels
    path: wheelhouse/*.whl
```
_Note: wildcard support has been added in v2 of the upload-artifact action, which is still in preview: https://github.com/actions/upload-artifact/issues/11#issuecomment-598812156._

You can also choose to use an action to upload to a private repository, or an FTP server.

**Comment by rcarcasses** [comment]
@RalfG thanks for your reply, I'll give a try to your advice.
