### ISSUE TITLE
Help How to register the path to setup.py

### ISSUE THREAD

**Issue by kotbegemot** [RalfG/python-wheels-manylinux-build#17]
I'm trying to pack my [project](https://github.com/cyberduckninja/RocketJoe) in wheels.
The recipe for the wheel is in a separate [repository](https://github.com/cyberduckninja/pip-RocketJoe/tree/60f5d1fe14892d892742b937ffd07335862f8b2f).

1. How to register the path to the setup.py in [workflow](https://github.com/cyberduckninja/pip-RocketJoe/blob/60f5d1fe14892d892742b937ffd07335862f8b2f/.github/workflows/pip.yml) ?
2. How to download the  [project](https://github.com/cyberduckninja/RocketJoe) source code and put it next to the setup.py?

**Comment by RalfG** [comment]
I think one of the problems you may have it that the Checkout action deletes everything in the directory in which it will checkout the second repository, unless you specify a `path`. You can try something similar to this solution: https://github.com/actions/checkout/issues/33#issuecomment-595988890

Next, in the python-wheels-manylinux-build action, you can specify the same path with the option `package-path`. Then the only caveat is that the setup.py script should know where to find the project (which will be either the parent directory of setup.py, or a subfolder of that parent directory, if `path` was also specified in the first actions/checkout).
