### ISSUE TITLE
Facing error "standard_init_linux.go:211: exec user process caused "exec format error"" while using RalfG/python-wheels-manylinux-build@v0.3-manylinux2014_aarch64 in github-actions with qemu

### ISSUE THREAD

**Issue by odidev** [RalfG/python-wheels-manylinux-build#21]
Hi,

I am trying to use `RalfG/python-wheels-manylinux-build@v0.3-manylinux2014_aarch64` image in github-actions to build manylinux wheels for aarch64 along with qemu, but I am facing error `standard_init_linux.go:211: exec user process caused "exec format error"` while building the image at step `RUN chmod +x /entrypoint.sh`, as it is building before running qemu.

Please suggest if I need to add anything to build this image. Thanks.

**Build report:** https://github.com/odidev/github-test/runs/930701151?check_suite_focus=true

**Suggestion:** As we are already setting `entrypoint.sh` to the executable mode, I think we can remove this step from the Dockerfile.

Please share your opinion on the same.

**Comment by RalfG** [comment]
Yes, that makes sense. It seems that it's not possible to run a command in the action workflow before the build steps, which is rather annoying. But if removing `RUN chmod +x /entrypoint.sh` does not make any difference, that that is an easy fix to the issue.

**Comment by odidev** [comment]
Yes, I have tested locally and it is working, as only this command is under RUN tag, which runs in shell. Do you want me to raise PR?

**Comment by RalfG** [comment]
Fix is available in v0.3.1. Thanks for the PR, @odidev!
