### ISSUE TITLE
Does it create wheels for Windows as well?

### ISSUE THREAD

**Issue by pssolanki111** [RalfG/python-wheels-manylinux-build#27]
I'm sure the title itself is clear. To explain, I need a build wheel for pyaudio for Py3.7 - 32 Bit - windows 10. I'm confused by the name 'manylinux'.  Can I make it work for Windows or is it just Linux? 

P.S I don't really need to put it on PyPi. Just need to install on my system.

Thanks You.

**Comment by RalfG** [comment]
This action is to create wheels for Linux only. For Windows, you can simply use the GitHub Actions [Windows runner](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on).

**Comment by pssolanki111** [comment]
Thank you for the information. Appreciate it :)
