### ISSUE TITLE
pypy images?

### ISSUE THREAD

**Issue by minrk** [RalfG/python-wheels-manylinux-build#30]
PyPy folks [maintain a manylinux2010 image](https://github.com/pypy/manylinux) which adds pypy installations to the pypa 2010 image, which would be handy to include here. Since these only add installations to the pypa 2010 image, the pypy 2010 image could be used *instead of* the upstream pypa 2010 without anything lost, but I can see why that might not be exactly what you want to do.

**EDIT:**

I believe all that needs to be added is one more list entry to `create_tags.py`, but it's complicated slightly by the fact that the image would come from `docker.io/pypywheels/manylinux2010-pypy_x86_64` instead of `quay.io/pypa/manylinux2010_x86_64`, unlike the rest

**Comment by RalfG** [comment]
Good suggestion. I would opt to add this to the list of "other supported manylinux containers", indeed by adding them to the list in create_tags.py: 

https://github.com/RalfG/python-wheels-manylinux-build/blob/34161e0af9394fc7b5140da1ae8fc861540bba8d/.github/workflows/create_tags.py#L8-L17

We should indeed edit this list to include the full image names (including docker.io and quay,io). Users will also have to configure the action in such a way that when using the pypy images, they use the correct python version tags, as defined in https://github.com/pypy/manylinux#pep-425-compatibility-tags. So an update of the documentation would also be in order. 

Feel free to open a PR if you can ;)

**Comment by RalfG** [comment]
@minrk PyPy is also available in the PyPI manylinux images: 
https://github.com/pypa/manylinux#image-content

These Python versions can be selected with the `python-versions` argument of the action. For instance:
```yaml
python-versions: 'pp37-pypy37_pp73 pp38-pypy38_pp73'
```
