### ISSUE TITLE
Question: how to use these images to test the packages just build?

### ISSUE THREAD

**Issue by dvarrazzo** [RalfG/python-wheels-manylinux-build#34]
Hello,

I am using your project to build setproctitle packages (see e.g. [this job](https://github.com/dvarrazzo/py-setproctitle/actions/runs/469233597))

I would be interested in testing the packages just built, so pretty much using the same images to run a `pip install PACKAGE` and a `pytest` or `tox`, with the tests available in the cloned repos and the package installed. The actions should run in the image, so we can test properly each architecture.

Any idea about how to do it?

Thank you very much!

**Comment by dvarrazzo** [comment]
> and a `pytest` or `tox`,

Actually, not tox, as it would create a further isolated environment, whereas it would be good to install the package in the "system" python (i.e. in the image) and run pytest on the installed artifact.

For instance, testing the sdist can be done with:

```
pip install "path/to/setproctitle-1.2.tar.gz[test]"
pytest
```

so the idea would be to run a similar command but inside the image.

**Comment by RalfG** [comment]
Hi @dvarrazzo,

Good question! This action's main purpose is to build manylinux python packages, which is done with the manylinux container images. Having multiple build environments for different system architectures is mostly a side effect of this.

I could add a `post-build-command` option, similar to the current `pre-build-command` option. This would allow users to run any arbitrary code after the package has been build. One complicating factor, however, is that the manylinux containers each contain all supported Python versions (https://github.com/pypa/manylinux), each installed in `opt/python/<version>`. So this is something users should take into account, if they would want to use this `post-build-command` option for testing.

You could also take a look at cibuildwheel - a slightly more elaborate project, compared to this little Action ;) - which supports testing as well: https://cibuildwheel.readthedocs.io/en/stable/options/#testing
