### ISSUE TITLE
Question: is it possible to change server to upload to test.pypi ?

### ISSUE THREAD

**Issue by lasofivec** [RalfG/python-wheels-manylinux-build#35]
Is it possible to change an option to upload to test.pypi instead of pypi ?

**Comment by RalfG** [comment]
This action does not upload the built wheels to PyPI, you need an additional step in your pipeline to do so.

If you are following the [full_workflow_example.yml](https://github.com/RalfG/python-wheels-manylinux-build/blob/master/full_workflow_example.yml), you can add `--repository testpypi` to the twine command (see [Using TestPyPI - Python packaging](https://packaging.python.org/guides/using-testpypi/)). You can also use the [official PyPI Publish action](https://github.com/pypa/gh-action-pypi-publish), which also supports TestPyPI.
