### ISSUE TITLE
Seeking help for use

### ISSUE THREAD

**Issue by GoodManWEN** [RalfG/python-wheels-manylinux-build#36]
Hi everyone,  I am trying to upload a project with C extensions to pypi, this is my first time uploading this kind of platform exclusive project, I have encountered some problems and need help.

I want to use github actions to help me automate the process of publishing my project to pypi, I managed to implement the windows version of the upload, but when coming to linux, I tried to use this repo, but there raised an error that I couldn't understand the error message.

My repo link is [GoodManWEN/py-fnvhash-c](https://github.com/GoodManWEN/py-fnvhash-c), where simplified version of the project tree structure is as follow:
```
.
├── fnvhash_c     #  pypi project name
│   ├── bfilt.py
│   └── __init__.py
├── LICENSE
├── README.md
├── requirements.txt
├── setup.cfg
├── setup.py
└── src
     ├── cityhash.pyx
     ├── cityhash_setup.py
     └──  include
          └── city.h
```
On windows system, in a full upload operation, I need to do the following commands:
```
cd src
cython cityhash_setup.py build_ext --inplace
move *.pyd ../fnvhash_c
cd ..
python setup.py bdist_wheel
twine upload dist/*
```
And then I tried to switch it into a many linux version, I used the following actions command:
```
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux1_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
        build-requirements: 'cython'
```
Got the error message:
```
Building wheels for collected packages: fnvhash-c
  Building wheel for fnvhash-c (setup.py): started
  Building wheel for fnvhash-c (setup.py): finished with status 'done'
  Created wheel for fnvhash-c: filename=fnvhash_c-dev-cp36-cp36m-linux_x86_64.whl size=4647 sha256=fc10cd549f184c78159b4dca9326676111cae7dafc6dc69b60c6b70a1adfc819
  Stored in directory: /tmp/pip-ephem-wheel-cache-yh13j51a/wheels/cb/ab/8f/fd29149f371a05d1292662735ad3569bffe7dbc23f93e70d91
  WARNING: Built wheel for fnvhash-c is invalid: Metadata 1.2 mandates PEP 440 version, but 'dev' is not
Failed to build fnvhash-c
ERROR: Failed to build one or more wheels
+ echo 'Building wheels failed.'
+ exit 1
Building wheels failed.
```
One thing I didn't quite understand through the docs is that, theoretically building a c++ plugin and building a pypi wheel are two different builds.When using this action repo, I'm not quite sure when the cython build command is supposed to happen.

How should I adjust my project to make it work properly? Thanks.

**Comment by RalfG** [comment]
Hi! You ran into an error from the `pip wheel` command. Apparently, in order to build a wheel, the version specified in `setup.py` needs to adhere to [PEP440](https://www.python.org/dev/peps/pep-0440/#version-scheme). You seem to have used `dev`. Can you try to use another version, e.g. `0.1.0-dev` and see if it works?

**Comment by GoodManWEN** [comment]
@RalfG Thanks for reply, I've tried to switch to a branch called `0.1.3` and the actions error summary shows in the following link
[https://github.com/GoodManWEN/py-fnvhash-c/runs/2063405751?check_suite_focus=true](https://github.com/GoodManWEN/py-fnvhash-c/runs/2063405751?check_suite_focus=true)

btw, if I'm understanding correctly, `python-wheels-manylinux-build` is using branch names to get the pypi version number, (compareing to the way I've always done it is to determine the version number by the release tag number), does this mean that if I want to use this repo to build wheels, the normative approach is to first create a new branch with the name of version number, and then trigger the actions on that branch?

**Comment by RalfG** [comment]
This action (`python-wheels-manylinux-build`) does not directly care about the version of the Python package you are trying to build. `pip wheel`, included in the [manylinux container images](https://github.com/pypa/manylinux), which this action uses, gets the version number from either the `setup.py` or the `pyproject.toml` file, not from the git branch.

In the current action run you posted, a new issue arrises. It seems like there is no compiled code in the wheel that was build, so the auditwheel tool cannot convert it to any manylinux-tagged wheel. This may be similar to the issue described here: https://github.com/pypa/auditwheel/issues/247#issuecomment-678790316
