### ISSUE TITLE
cp38-cp38m error. do not find pip 

### ISSUE THREAD

**Issue by somewheve** [RalfG/python-wheels-manylinux-build#38]
hey, i am try to build python package  and use your marketpalce, but i find it can't find pip of python38

here is the log 
```
+ for PY_VER in '"${arrPY_VERSIONS[@]}"'
+ /opt/python/cp38-cp38m/bin/pip install --upgrade --no-cache-dir pip
/entrypoint.sh: line 30: /opt/python/cp38-cp38m/bin/pip: No such file or directory

```

how can i  solve it ? 
```
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38m cp39-cp39m'
```

**Comment by innerNULL** [comment]
So if this problem finally solved? thanks

**Comment by somewheve** [comment]
yea,  it's my problem, cp38 not cp38m,  lol

inull ***@***.***> 于2021年9月3日周五 下午10:46写道：
