### ISSUE TITLE
Can't find Python Header Files

### ISSUE THREAD

**Issue by coreyjadams** [RalfG/python-wheels-manylinux-build#55]
Hi,

Thanks for creating this github action and maintaining it - really appreciated!

I am trying to use it to build a C++ extension that builds with CMake.  I've hit an issue that I'm not 100% sure how to fix - my package requires the Python header files, but CMake isn't finding them:

```
  CMake Error at /tmp/pip-build-env-6h7f921u/overlay/lib/python3.6/site-packages/cmake/data/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find Python (missing: Python_LIBRARIES Development
    Development.Embed) (found suitable version "3.6.15", minimum required is
    "3.6.15")
```

It clearly finds the right version of python;  are the Development components also installed in the container?  Apologies if I'm just doing something wrong (which is most likely!).

**Comment by RalfG** [comment]
Could you share the workflow file you are using when encountering this issue?

The manylinux containers include multiple Python versions in the `/opt/python/<python tag>-<abi tag>` directories (see https://github.com/pypa/manylinux#image-content). I'm not immediately sure what is going wrong here.
