### ISSUE TITLE
Action runs pip as root

### ISSUE THREAD

**Issue by droodev** [RalfG/python-wheels-manylinux-build#58]
Running everything as root can break the next actions in the pipeline.

In my case the issue was caused by the fact that for my package, say `foobar`, the `.egg-file` created in the `src` directory was created by this action and had rights only for root; see the output of `ls -al`
```bash
drwxr-xr-x 4 runner docker 4096 Nov 10 10:13 .
drwxr-xr-x 5 runner docker 4096 Nov 10 10:13 ..
drwxr-xr-x 2 root   root   4096 Nov 10 10:13 foobar.egg-info
```
Later in the workflow, I also build an sdist using `python -m build --sdist`. When `setuptools` then tries to use the `.egg-file`, it cannot have rights to do so.

Importantly, I have several packages and this error only pops out for the one one that has a C++ extension.

If there is hope to fix this issue, I am happy to deliver a small demo package, or a whole repo, which will demonstrate the issue.

**Comment by droodev** [comment]
A small workaround that still allows keeping everything in a single `.yml` file (note that it might not be desirable) is to run the manylinux action after running the sdist action.

**Comment by RalfG** [comment]
Hi @droodev,

Thanks for reporting this issue. Could you check if adding this action to your workflow before the manylinux action solves the issue?

Best,
Ralf

**Comment by droodev** [comment]
Hi @RalfG,

I confirm that adding the action that builds the sdist before the manylinux action sovles the issue. I believe that then the manylinux action does not create the `.egg-info` directory. So, it does not have root as the owner.

Best,
Andrzej

**Comment by RalfG** [comment]
Hi @droodev,

Apologies, I meant to link to this action: https://github.com/ScribeMD/rootless-docker. Does adding this in front of the manylinux action fix the issue as well?

Thanks for testing!
Ralf

**Comment by droodev** [comment]
I experimented with the action you pointed me to. It does not help unfortunately---the error persists.
