### ISSUE TITLE
"find: unrecognized: -iregex" (musllinux_1_1_x86_64)

### ISSUE THREAD

**Issue by mr-c** [RalfG/python-wheels-manylinux-build#61]
https://github.com/common-workflow-language/schema_salad/actions/runs/3938642519/jobs/6737576186#step:9:570

I guess an `apd add findutils` is needed somewhere?

**Comment by mr-c** [comment]
As a workaround, trying `system-packages: findutils` gives
```
 + command -v apt-get
+ command -v yum
+ echo 'Package managers apt or yum not found.'`
```
Would be nice if `apk` was added to the list..

**Comment by RalfG** [comment]
Thanks for the PR, @mr-c! (#62)

**Comment by mr-c** [comment]
Thanks @RalfG ; can you automatically add a `system-packages: findutils` or equivalent for `musllinux_1_1_x86_64` users? It will save them some headache :-)

**Comment by RalfG** [comment]
Apologies, I did not realize that `findutils` was required by the action itself. v0.7.1 now installs findutils by default and additionally fixes a bug where the use of sh instead of bash resulted in issues on musllinux containers.

**Comment by mr-c** [comment]
Thank you @RalfG !

**Comment by mr-c** [comment]
If you have any advice for what failed my build with 0.7.1 ; it would be welcome 

https://github.com/common-workflow-language/schema_salad/actions/runs/3999677201/jobs/6863864899#step:9:614

https://github.com/common-workflow-language/schema_salad/actions/runs/3999677201/jobs/6863864899#step:10:529

Did a file get copied to the wrong directory?

**Comment by RalfG** [comment]
I think the issue is that after the first build, the consecutive builds reuse some of the previously compiled files. Maybe there is a way to force `pip wheel` to do a full rebuild, or you can manually remove those files between builds for the different platforms (e.g., the `build` dir).

**Comment by mr-c** [comment]
@RalfG Hmm.. there is no `post-build-command` option and outside the container one lacks permissions to move files outside of `dist`: https://github.com/common-workflow-language/schema_salad/actions/runs/4024224052/jobs/6916008349

I'll see what I can do with setting `pip-wheel-args` to something likle `-w ./dist_musllinux --no-deps` (but obviously that is fragile)

(Thanks again for this GitHub Action and your help!)

**Comment by mr-c** [comment]
Hmm.. the wheels (and fixed-up wheels) got written to `./dist_musllinux`,

https://github.com/common-workflow-language/schema_salad/actions/runs/4024396814/jobs/6916379545#step:9:612

but later there are still problems with `RalfG/python-wheels-manylinux-build@v0.7.1-manylinux2014_x86_64`

https://github.com/common-workflow-language/schema_salad/actions/runs/4024396814/jobs/6916379545#step:10:569

I'll try re-ordering the builds next. The last thing I can think of is a matrix build and uploading separately

**Comment by mr-c** [comment]
So I fixed this by completely splitting the config up into separate jobs. Alas, since the action name field (`uses`) is not allowed to be parameterized by a GitHub Action Expression, one can't use a Matrix to iterate this way.

https://github.com/common-workflow-language/schema_salad/blob/13395631183f7788c7a3a143051d8b3f298b09eb/.github/workflows/wheels.yml

Thanks again for your help!
