### ISSUE TITLE
cp311-cp311/bin/pip: No such file or directory

### ISSUE THREAD

**Issue by cdgriffith** [RalfG/python-wheels-manylinux-build#63]
Have tried versions 0.6.0, 0.7.0 and 0.7.1 and getting the same error on all, three that it can't find pip for 3.11

```
+ for PY_VER in '"${arrPY_VERSIONS[@]}"'
+ /opt/python/cp311-cp311/bin/pip install --upgrade --no-cache-dir pip
/entrypoint.sh: line 44: /opt/python/cp311-cp311/bin/pip: No such file or directory
```

**Comment by jnwatson** [comment]
I found my problem that caused this at least. I had missed references to an old version of this package in my workflow. Easy fix, e.g. https://github.com/jnwatson/py-lmdb/pull/339/commits/c51a72256f1970b4adf782aaa2c46c69903398a0
