### ISSUE TITLE
Do not build wheels for dependencies

### ISSUE THREAD

**Issue by RalfG** [RalfG/python-wheels-manylinux-build#8]
Currently when wheels are build, dependency wheels are build with it, which (I think) is not necessary. Further, this means that auditwheel will try to fix these wheels as well, which can lead to unexpected problems.

Adding `--no-deps` to `pip wheel` should fix this.

@pedrocamargo, following up on your previous issue (#1), I noticed that in [a later build](https://github.com/AequilibraE/aequilibrae/runs/451883551#step:7:254) the action tried to auditwheel PyQt5, which was missing a dependency, which made the action error and exit... Fixing this, should fix your problem.

**Comment by RalfG** [comment]
@pedrocamargo: running the action with v0.2.2-manylinux2014_x86_64 should now work for your package

**Comment by pedrocamargo** [comment]
Absolutely brilliant work!  Thank you!
